dist: trusty
language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

before_install: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || openssl aes-256-cbc -K $encrypted_cd479e0d238b_key -iv $encrypted_cd479e0d238b_iv -in keystore.jks.enc -out keystore.jks -d'
install: ./gradlew build -S
after_success: ./gradlew jacocoTestReport coveralls

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/CommonCapabilities
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      all_branches: true
      repo: CyclopsMC/CommonCapabilities
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/CommonCapabilities
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build/docs/javadoc
    on:
      all_branches: true
      repo: CyclopsMC/CommonCapabilities
      condition: "$TRAVIS_BRANCH =~ ^(master).*$"
