# Project
mod_version=2.11.7
group=org.cyclops.commoncapabilities
java_version=25

# Common
minecraft_version=26.1.2
mod_name=CommonCapabilities
mod_author=rubensworks (aka kroeser)
mod_id=commoncapabilities
license=MIT
github_url=https://github.com/CyclopsMC/CommonCapabilities
issue_tracker_url=https://github.com/CyclopsMC/CommonCapabilities/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/commoncapabilities
description=Capabilities that can be shared by multiple mods.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=247007
modrinth_project_id=oFXrCkDI

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/common-capabilities.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.29.5-1012
rfapi_version=1.12-2.1.0.7
enderio_version=3.0.0.40_alpha
endercore_version=0.4.0.24-alpha
mantle_version=1.12-1.3.3.48
tconstruct_version=1.12.2-2.12.0.126
forestry_version=5.8.2.387
buildcraft_version=7.99.23
IC2_version=2.7.37-ex111
thermalexpansion_version=1.12.2-5.5.3.41
cofhcore_version=1.12.2-4.6.2.25
thermalfoundation_version=1.12.2-2.6.2.26
cofhworld_version=1.12.2-1.3.0.6
codechickenlib_version=1.12.2-3.2.2.354
visualworkbench_version=8004807
puzzleslib_version=7999119
