modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/CommonCapabilities/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/commoncapabilities"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="commoncapabilities"
version="${file.jarVersion}"
displayName="CommonCapabilities"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/commoncapabilities.json"
description='''
Forge Capabilities that can be shared by multiple mods.
'''
[[dependencies.commoncapabilities]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.commoncapabilities]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.commoncapabilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
