modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/CommonCapabilities/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/commoncapabilities"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="commoncapabilities"
version="${file.jarVersion}"
displayName="CommonCapabilities"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/common-capabilities.json"
description='''
Forge Capabilities that can be shared by multiple mods.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.commoncapabilities]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.commoncapabilities]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.commoncapabilities]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
